# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Cache
      uses: actions/cache@v2.1.6
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: ~/.m2/repository
        # An explicit key for restoring and saving the cache
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn -B install --file pom.xml

    - name: Copy Artifacts
      run: |
        cd ${{ github.workspace }}; rm -rf artifacts; mkdir -p artifacts; find . -name "*.jar" -type f -exec cp {} ./artifacts \;

    - name: Upload file
      uses: actions/upload-artifact@v2.2.0
      with:
        name: mercury-maven-build-artifacts
        path: |
          ${{ github.workspace }}/artifacts
